/**
 * Created by DvandeLindt on 20-12-2016.
 */

public with sharing class CustomerMapper implements ICustomerMapper {

    public Customers__x getCustomerById( String id ) {
        Customers__x customer;
        
        return customer;
    }
    
    public List<Customers__x> getCustomersByRegion( String region ) {
        List<Customers__x> customers;
        
        return customers;
    }
}